name: lost_found_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^2.27.2
  firebase_auth: ^4.18.0
  get: ^4.6.6
  flutter_launcher_icons: ^0.13.1
  fluttertoast: ^8.2.4
  internet_connection_checker: ^1.0.0+1
  cloud_firestore: ^4.15.10
  cloud_firestore_web: ^3.10.10
  cool_dropdown: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/lost and found icon.png"

  flutter_lints: ^3.0.2

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
