// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5z8yQm6PkQfhapwSylnVXccyWvWqnQt4',
    appId: '1:975298544164:web:54998ddf223a9026f34eb1',
    messagingSenderId: '975298544164',
    projectId: 'lost-and-found-app-7b29b',
    authDomain: 'lost-and-found-app-7b29b.firebaseapp.com',
    storageBucket: 'lost-and-found-app-7b29b.appspot.com',
    measurementId: 'G-1ZZ6J1RJXV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeGwa0TA4uHprGKhdrOqhF5PrHnpTL0bM',
    appId: '1:975298544164:android:dcbbff0a383c05d9f34eb1',
    messagingSenderId: '975298544164',
    projectId: 'lost-and-found-app-7b29b',
    storageBucket: 'lost-and-found-app-7b29b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyolhPT0oKextTSXBK6cvdYXWLA-krt_I',
    appId: '1:975298544164:ios:d1c261ab06e94a9df34eb1',
    messagingSenderId: '975298544164',
    projectId: 'lost-and-found-app-7b29b',
    storageBucket: 'lost-and-found-app-7b29b.appspot.com',
    iosBundleId: 'com.example.lostFoundApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyolhPT0oKextTSXBK6cvdYXWLA-krt_I',
    appId: '1:975298544164:ios:dc254269d15a68bdf34eb1',
    messagingSenderId: '975298544164',
    projectId: 'lost-and-found-app-7b29b',
    storageBucket: 'lost-and-found-app-7b29b.appspot.com',
    iosBundleId: 'com.example.lostFoundApp.RunnerTests',
  );
}
